[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "EnhancedCooldowns"
description = "Enhances cooldown mechanics for throwables and wingsuit salvo with configurable activation modes."
websiteUrl = "https://github.com/Little-Sparroh/EnhancedCooldowns"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/EnhancedCooldowns.dll"
target = "BepInEx/plugins/EnhancedCooldowns.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
